apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::805711586344:role/project-bedrock-cluster-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::805711586344:user/bedrock-dev-view
      username: bedrock-dev-view
      groups:
        - view-group
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-07T17:15:40Z"
  name: aws-auth
  namespace: kube-system